### ISSUE TITLE
Fatal errors on WordPress 5.2.2 & php 7.3.7

### ISSUE THREAD

**Issue by Remzi1993** [second-2None/service-area-postcode-checker#2]
Hi @second-2None 

Your plugin does not work on WordPress 5.2.2 & php 7.3.7.
I got some fatal errors after changing some settings.
I hope you will have time to make this plugin compatible with WordPress 5.2.2 and/or php 7.3.7

Kind regards,
Remzi

**Comment by Kane-R-G** [comment]
Are these the same errors you are having in the other issue?

**Comment by Remzi1993** [comment]
@second-2None No, the errors on the other issue #1 is not related to this issue.
These errors happen when I try to enter some settings.

**Comment by Kane-R-G** [comment]
I'd need to know what the fatal errors are before I can fix them?

**Comment by Remzi1993** [comment]
@second-2None I will check this weekend. I'm very busy, maybe you could check this out? Just install php 7 (with all display_errors turned on in php.ini) and the latest WP version.

**Comment by Kane-R-G** [comment]
I think I've found them, Ill be pushing an update (2.0.8) in the next day or two with some fixes and new additions. It will fix your other issue as well.

**Comment by Remzi1993** [comment]
@second-2None Thank you very much 👍

**Comment by Kane-R-G** [comment]
This has been fixed in version 2.0.8

**Comment by Remzi1993** [comment]
@second-2None Thank you!
